apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-server 
spec:
  capacity:
    storage: 5G
  accessModes:
  - ReadWriteMany
  claimRef:
    namespace: default
    name: redis-server-claim
  nfs:
    path: /exports
    server: 10.233.1.175
